### ISSUE TITLE
Cannot start

### ISSUE THREAD

**Issue by WayfaringCookie** [VikingTheDev/pAnticheat#1]
[ citizen-server-impl] Running build tasks on resource pAnticheat - it'll restart once completed.
[ citizen-server-impl] Couldn't start resource pAnticheat.
yarn install v1.22.5
info No lockfile found.
[1/4] Resolving packages...
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[ citizen-server-impl] Building resource pAnticheat failed.
[ citizen-server-impl] Error data: yarn failed!

**Comment by augustsh** [comment]
Seems like an issue with yarn not the script. Try adding ``ensure yarn`` before pAnticheat in your ``server.cfg``

**Comment by VikingTheDev** [comment]
I actually had a friend run into the same issue, make sure you have git installed on the VPS/your computer @WayfaringCookie.

**Comment by augustsh** [comment]
If you run into this issue with yarn download [git](https://git-scm.com/downloads). After downloading and installing git, do a full server restart (close the server completely down, don't just restart through Tx)
